name: E2E BDD (Behave + Playwright)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave playwright

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Start Streamlit app (background)
        run: |
          nohup streamlit run app.py --server.headless true --server.port 8501 --server.address 127.0.0.1 > streamlit.log 2>&1 &
          sleep 3

      - name: Wait until app is ready
        run: |
          python - << 'PY'
          import time, urllib.request
          url = "http://127.0.0.1:8501"
          for _ in range(60):
              try:
                  urllib.request.urlopen(url, timeout=2)
                  print("App is ready:", url)
                  raise SystemExit(0)
              except Exception:
                  time.sleep(1)
          raise SystemExit("App did not start in time")
          PY

      - name: Run BDD tests (Behave)
        run: |
          behave -f pretty --no-capture

      - name: Upload Streamlit log (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-log
          path: streamlit.log
